include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance: const ueberall wo moeglich
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Code-Qualitaet
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_new: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_build_context_synchronously: true

    # Null-Safety
    avoid_null_checks_in_equality_operators: true
    unnecessary_null_checks: true

    # Imports
    directives_ordering: true
    always_use_package_imports: true

    # Typen
    avoid_dynamic_calls: false
    prefer_typing_uninitialized_variables: true

analyzer:
  errors:
    # Warnungen statt Fehler fuer schrittweise Behebung
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_final_locals: info
    prefer_single_quotes: info
    sort_child_properties_last: info
    directives_ordering: info
    always_use_package_imports: info
    avoid_print: info
  exclude:
    # Generierter Code nicht pruefen
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"
